language: objective-c
xcode_project: CleanroomDataTransactions.xcodeproj
osx_image: xcode7.3

install:
  gem install xcpretty

#
# Note: Unit test scripts commented out due to a problem reliably launching the
#       simulator from the command line. See:
#
#       https://github.com/travis-ci/travis-ci/issues/3040
#
# A possible work-around; not yet tested:
#
#       before_install: open -b com.apple.iphonesimulator
#

script:
  - xcodebuild -project CleanroomDataTransactions.xcodeproj -scheme CleanroomDataTransactions-iOS -destination 'platform=iOS Simulator,OS=9.3,name=iPhone 6' clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
#  - xcodebuild -project CleanroomDataTransactions.xcodeproj -scheme CleanroomDataTransactions-iOS -destination 'platform=iOS Simulator,OS=9.3,name=iPhone 6' test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
  - xcodebuild -project CleanroomDataTransactions.xcodeproj -scheme CleanroomDataTransactions-OSX -destination 'platform=OS X' clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
#  - xcodebuild -project CleanroomDataTransactions.xcodeproj -scheme CleanroomDataTransactions-OSX -destination 'platform=macOS' test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
  - xcodebuild -project CleanroomDataTransactions.xcodeproj -scheme CleanroomDataTransactions-tvOS -destination 'platform=tvOS Simulator,OS=9.2,name=Apple TV 1080p' clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
#  - xcodebuild -project CleanroomDataTransactions.xcodeproj -scheme CleanroomDataTransactions-tvOS -destination 'platform=tvOS Simulator,OS=9.2,name=Apple TV 1080p' test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
  - xcodebuild -project CleanroomDataTransactions.xcodeproj -scheme CleanroomDataTransactions-watchOS -destination 'platform=watchOS Simulator,OS=2.2,name=Apple Watch - 42mm' clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
