language: objective-c
xcode_project: CleanroomDataTransactions.xcodeproj
osx_image: xcode8

git:
  depth: 1
  submodules: false

before_install:
  git submodule update --init

install:
  gem install xcpretty

script:
- set -o pipefail && xcodebuild -project CleanroomDataTransactions.xcodeproj -scheme CleanroomDataTransactions-iOS -destination 'platform=iOS Simulator,OS=10.0,name=iPhone 7' clean test | xcpretty
- set -o pipefail && xcodebuild -project CleanroomDataTransactions.xcodeproj -scheme CleanroomDataTransactions-OSX -destination 'platform=macOS' clean test | xcpretty
- set -o pipefail && xcodebuild -project CleanroomDataTransactions.xcodeproj -scheme CleanroomDataTransactions-tvOS -destination 'platform=tvOS Simulator,OS=10.0,name=Apple TV 1080p' clean test | xcpretty
- set -o pipefail && xcodebuild -project CleanroomDataTransactions.xcodeproj -scheme CleanroomDataTransactions-watchOS -destination 'platform=watchOS Simulator,OS=3.0,name=Apple Watch - 42mm' clean build | xcpretty


after_success:
  sleep 20
