language: objective-c
xcode_project: CleanroomDataTransactions.xcodeproj
osx_image: xcode8

git:
  depth: 1
  submodules: false

before_install:
  - git submodule update --init

install:
  - gem install xcpretty

script:
- set -o pipefail && xcodebuild -project CleanroomDataTransactions.xcodeproj -configuration Release ONLY_ACTIVE_ARCH=YES -scheme CleanroomDataTransactions-iOS -destination 'platform=iOS Simulator,OS=10.0,name=iPhone 6s Plus' -destination-timeout 300 clean build | tee "CleanroomDataTransactions-iOS-build.log" | xcpretty
- set -o pipefail && xcodebuild -project CleanroomDataTransactions.xcodeproj -configuration Release ONLY_ACTIVE_ARCH=YES -scheme CleanroomDataTransactions-iOS -destination 'platform=iOS Simulator,OS=10.0,name=iPhone 6s Plus' -destination-timeout 300 test | tee "CleanroomDataTransactions-iOS-test.log" | xcpretty
- set -o pipefail && xcodebuild -project CleanroomDataTransactions.xcodeproj -configuration Release ONLY_ACTIVE_ARCH=YES -scheme CleanroomDataTransactions-OSX -destination 'platform=macOS' -destination-timeout 300 clean build | tee "CleanroomDataTransactions-macOS-build.log" | xcpretty
- set -o pipefail && xcodebuild -project CleanroomDataTransactions.xcodeproj -configuration Release ONLY_ACTIVE_ARCH=YES -scheme CleanroomDataTransactions-OSX -destination 'platform=macOS' -destination-timeout 300 test | tee "CleanroomDataTransactions-macOS-test.log" | xcpretty
- set -o pipefail && xcodebuild -project CleanroomDataTransactions.xcodeproj -configuration Release ONLY_ACTIVE_ARCH=YES -scheme CleanroomDataTransactions-tvOS -destination 'platform=tvOS Simulator,OS=10.0,name=Apple TV 1080p' -destination-timeout 300 clean build | tee "CleanroomDataTransactions-tvOS-build.log" | xcpretty
- set -o pipefail && xcodebuild -project CleanroomDataTransactions.xcodeproj -configuration Release ONLY_ACTIVE_ARCH=YES -scheme CleanroomDataTransactions-tvOS -destination 'platform=tvOS Simulator,OS=10.0,name=Apple TV 1080p' -destination-timeout 300 test | tee "CleanroomDataTransactions-tvOS-test.log" | xcpretty
- set -o pipefail && xcodebuild -project CleanroomDataTransactions.xcodeproj -configuration Release ONLY_ACTIVE_ARCH=YES -scheme CleanroomDataTransactions-watchOS -destination 'platform=watchOS Simulator,OS=3.0,name=Apple Watch - 42mm' -destination-timeout 300 clean build | tee "CleanroomDataTransactions-watchOS-build.log" | xcpretty

after_failure:
- echo "Travis test result is $TRAVIS_TEST_RESULT"
- printf "\niOS build log:\n"
- cat "CleanroomDataTransactions-iOS-build.log"
- printf "\niOS test log:\n"
- cat "CleanroomDataTransactions-iOS-test.log"
- printf "\nmacOS build log:\n"
- cat "CleanroomDataTransactions-macOS-build.log"
- printf "\nmacOS test log:\n"
- cat "CleanroomDataTransactions-macOS-test.log"
- printf "\ntvOS build log:\n"
- cat "CleanroomDataTransactions-tvOS-build.log"
- printf "\ntvOS test log:\n"
- cat "CleanroomDataTransactions-tvOS-test.log"
- printf "\nwatchOS build log:\n"
- cat "CleanroomDataTransactions-watchOS-build.log"

